name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      - name: Instantiate deps
        run: |
          julia --project=@. -e 'import Pkg; Pkg.instantiate()'

      - name: Build docs (Documenter.jl)
        run: |
          if [ -f docs/make.jl ]; then
            julia --project=docs -e 'import Pkg; Pkg.instantiate(); include("docs/make.jl")'
          else
            echo 'No docs/make.jl — skipping docs build'
          fi
